version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DATABASE=smart-locker-api
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  prisma:
    image: prismagraphql/prisma:1.14
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            active: true
            host: db
            port: 5432
            user: user
            password: password