version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.11.1

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  check-typescript:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build typescript
          command: yarn check-typescript

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test

  semantic-release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Semantic release
          command: yarn semantic-release
      - persist_to_workspace:
          root: ~/repo
          paths:
            - package.json

  build-docker:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build Docker image
          command: docker build --cache-from=app -t app .
      - deploy:
          name: Push Docker image
          command: |
            export NPM_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag app smartlock/smart-locker-api:${NPM_PACKAGE_VERSION}
            docker push smartlock/smart-locker-api:${NPM_PACKAGE_VERSION}



workflows:
  version: 2
  build-test-release:
    jobs:
      - install-dependencies
      - check-typescript:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - semantic-release:
          requires:
            - check-typescript
            - test
            - lint
      - build-docker:
          requires:
            - semantic-release
      




  # build-test-publish:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  #           yarn install
  #     - run:
  #         name: Typescript
  #         command: yarn check-typescript
  #     - run:
  #         name: Lint
  #         command: yarn lint
  #     - run:
  #         name: Test
  #         command: yarn test
  #     - run:
  #         name: Semantic release
  #         command: |
  #           yarn semantic-release
  #     - setup_remote_docker
  #     - run:
  #         name: Build application Docker image
  #         command: |
  #           docker build --cache-from=app -t app .
  #     - deploy:
  #         name: Push application Docker image
  #         command: |
  #           export NPM_PACKAGE_VERSION=$(node -pe "require('./package.json').version")
  #           docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
  #           docker tag app formicarium/tanajura:${NPM_PACKAGE_VERSION}
  #           docker push formicarium/tanajura:${NPM_PACKAGE_VERSION}